# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# azure-pipelines.yml
trigger:
- main  # Cambia 'main' por tu rama principal si es diferente

pool:
  vmImage: 'windows-latest'  # Cambia la imagen según tus necesidades

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Cambia la versión según el SDK que uses
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build <tu_proyecto>.sln  # Cambia '<tu_proyecto>' por el nombre de tu solución
  displayName: 'Build Project'
